name: Snowflake CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute Snowflake script
        uses: snowflakedb/snowflake-action@v1
        with:
          account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          username: ${{ secrets.SNOWFLAKE_USER }}
          password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          database: mydatabase
          script-file: ./scripts/my-script.sql
