name: Snowflake CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-connector-python

    - name: Run SQL scripts and deploy to Snowflake
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_ENV }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_ENV }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_ENV }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_ENV }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_ENV }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_ENV }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA_ENV }}
      run: |
        python snowflake_pipeline.py
