name: Snowflake CI/CD Workflow

on:
  push:
    paths:
      - 'sql_scripts/**/*.sql'      
  pull_request:
    paths:
      - 'sql_scripts/**/*.sql'

jobs:
  execute_sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history to get the list of changed files

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-connector-python

    - name: Get changed .sql files
      id: get_changed_sql
      run: |
        echo "changed_sql_files" >> $GITHUB_ENV
        git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.sha }} -- sql_scripts/**/*.sql | xargs -I {} echo {} | xargs
        echo "EOF" >> $GITHUB_ENV

    - name: Execute .sql files on Snowflake
      if: ${{ env.changed_sql_files }}
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      run: |
        python snowflake_pipeline3.py
